version: "3"
services:  
  postgres: 
    image: "postgres:latest"
  redis: 
    image: "redis:latest"
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./client:/app  
  worker: 
    build: 
      context: ./worker
      dockerfile: Dockerfile.dev
    volumes:
        - /app/node_modules
        - ./worker:/app
  api: 
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment: 
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGHOST=postgres
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always  
    ports:
      - '3050:80'